[package]
name = "samp-sdk"
version = "2.1.0"
authors = ["ZOTTCE <zottce@gmail.com>", "NullSablex"]
description = "Bindings for C SA:MP SDK"
license = "MIT"
repository = "https://github.com/NullSablex/rust-samp"
readme = "../README.md"
edition = "2024"

[features]
default = []
encoding = ["encoding_rs"]

[dependencies]
bitflags = "2.10"
encoding_rs = { version = "0.8", optional = true }

[package.metadata.docs.rs]
features = ["encoding"]
default-target = "i686-pc-windows-msvc"
