[package]
name = "plugin"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
samp = { path = "../samp", features = ["encoding"] }
memcache = "0.19"
log = "0.4"
fern = "0.7"